### ISSUE TITLE
2.0 Roadmap

### ISSUE THREAD

**Issue by wgyt** [wgyt/wgytbot#22]
# 2.0 Roadmap 🥳 
## TODO:

- [x] Bug test to death | #24 

- [x] Update Codeowners to include @Namirah-Rahman |  #23 

- [x] Fix Oauth callback URL
- [x] Add changelog link to website

- [x] Add open-source link to website

- [x] Add wiki documentation

- [x] Add MIT licence | #29 

- [x] Finalize Every command | #25

- [x]  Listen To Spanish Teacher and make it go AAAAAAAAAA (website) IS DOWN WITH STATUS (status code) #31

**Comment by wgyt** [comment]
Item 3 solved by #23

**Comment by wgyt** [comment]
Item 7 solved by #25 and #26

**Comment by wgyt** [comment]
Item 1: @Namirah-Rahman found no bugs 🥳

**Comment by wgyt** [comment]
Items 3+4 are solved by #27

**Comment by wgyt** [comment]
Wiki done

**Comment by wgyt** [comment]
Licence added

**Comment by wgyt** [comment]
Solved it all :) Time to close this and publish 2.0
